"""Standalone BWT901BLE worker using the existing pure frame decoder."""

from __future__ import annotations

import asyncio
import queue
import sys
import threading
import time
from contextlib import suppress
from dataclasses import dataclass
from typing import Any

from DeviceInterface.bwt901_protocol import BWT901Packet, BWT901StreamDecoder

try:
    from bleak import BleakClient as _BleakClient
    from bleak import BleakScanner as _BleakScanner
    from bleak.exc import BleakDeviceNotFoundError as _BleakDeviceNotFoundError
except ImportError:  # pragma: no cover - depends on local runtime
    _BleakClient = None
    _BleakScanner = None
    _BleakDeviceNotFoundError = None


DEFAULT_BWT901_NOTIFY_UUID = "0000ffe4-0000-1000-8000-00805f9a34fb"
DEFAULT_BWT901_SCAN_TIMEOUT_S = 10.0

BWT901Record = dict[str, object]

# Multiple Windows BLE scan/connect operations have proven less reliable when
# performed concurrently.  This only serializes BWT901 discovery/connection;
# workers remain otherwise independent once connected.
_BLE_CONNECT_LOCK = threading.Lock()


@dataclass(frozen=True, slots=True)
class BWT901BLEConfig:
    """Connection settings for one physical BWT901BLE device."""

    device_id: str
    address: str = ""
    name_filter: str = "WT"
    notify_uuid: str = DEFAULT_BWT901_NOTIFY_UUID
    scan_timeout_s: float = DEFAULT_BWT901_SCAN_TIMEOUT_S
    windows_address_type: str | None = None

    def __post_init__(self) -> None:
        device_id = self.device_id.strip()
        address = self.address.strip()
        name_filter = self.name_filter.strip()
        notify_uuid = self.notify_uuid.strip()

        if not device_id:
            raise ValueError("BWT901 device_id must not be empty.")
        if not address and not name_filter:
            raise ValueError("BWT901 address and name_filter cannot both be empty.")
        if not notify_uuid:
            raise ValueError("BWT901 notify_uuid must not be empty.")
        if self.scan_timeout_s <= 0:
            raise ValueError("BWT901 scan_timeout_s must be positive.")
        if self.windows_address_type not in (None, "public", "random"):
            raise ValueError(
                "windows_address_type must be None, 'public', or 'random'."
            )

        object.__setattr__(self, "device_id", device_id)
        object.__setattr__(self, "address", address)
        object.__setattr__(self, "name_filter", name_filter)
        object.__setattr__(self, "notify_uuid", notify_uuid)
        object.__setattr__(self, "scan_timeout_s", float(self.scan_timeout_s))


def _record_from_packet(
    packet: BWT901Packet,
    *,
    host_monotonic_ns: int,
    host_unix_ns: int,
) -> BWT901Record:
    """Preserve one decoded frame and its host-observation boundary."""

    return {
        # This sequence is generated by BWT901StreamDecoder, not transmitted by
        # the device.  Keep the name explicit so callers do not mistake it for
        # a device sample counter.
        "decoder_sequence": packet.sequence,
        "host_monotonic_ns": host_monotonic_ns,
        "host_unix_ns": host_unix_ns,
        "acceleration_g": (
            packet.acc_x_g,
            packet.acc_y_g,
            packet.acc_z_g,
        ),
        "gyroscope_dps": (
            packet.gyro_x_dps,
            packet.gyro_y_dps,
            packet.gyro_z_dps,
        ),
        "euler_angle_deg": (
            packet.angle_x_deg,
            packet.angle_y_deg,
            packet.angle_z_deg,
        ),
        "raw_int16": packet.raw,
    }


class BWT901BLEWorker(threading.Thread):
    """Own one BLE connection and publish decoded BWT901 frame observations."""

    def __init__(
        self,
        config: BWT901BLEConfig,
        records: queue.Queue[BWT901Record] | None = None,
        *,
        client_factory: Any = None,
        scanner_factory: Any = None,
        not_found_error: Any = None,
    ) -> None:
        super().__init__(name=f"BWT901BLEWorker-{config.device_id}", daemon=True)
        self.config = config
        self.records = records if records is not None else queue.Queue()
        self.client_factory = _BleakClient if client_factory is None else client_factory
        self.scanner_factory = _BleakScanner if scanner_factory is None else scanner_factory
        self.not_found_error = (
            _BleakDeviceNotFoundError if not_found_error is None else not_found_error
        )

        self.stop_event = threading.Event()
        self.startup_event = threading.Event()
        self.stopped_event = threading.Event()
        self.error: BaseException | None = None

        self.decoder = BWT901StreamDecoder()
        self.notification_count = 0
        self.decoded_frame_count = 0
        self.resolved_address = ""
        self.resolved_name = ""

        self._callback_error: BaseException | None = None
        self._disconnected_event = threading.Event()

    def request_stop(self) -> None:
        """Request cooperative shutdown without waiting for BLE cleanup."""

        self.stop_event.set()

    def close(self, timeout_s: float = 5.0) -> None:
        """Single-worker convenience API: request stop, wait, surface failure."""

        if timeout_s <= 0:
            raise ValueError("timeout_s must be positive.")
        if threading.current_thread() is self:
            raise RuntimeError("A BWT901BLEWorker cannot join itself.")
        self.request_stop()
        if self.ident is not None:
            self.join(timeout_s)
        if self.is_alive():
            raise TimeoutError(
                f"BWT901 worker {self.config.device_id!r} did not stop before timeout_s."
            )
        if self.error is not None:
            raise RuntimeError(
                f"BWT901 worker {self.config.device_id!r} failed."
            ) from self.error

    def run(self) -> None:
        try:
            asyncio.run(self._run_async())
        except BaseException as exc:
            self.error = exc
            self.stop_event.set()
        finally:
            self.startup_event.set()
            self.stopped_event.set()

    async def _run_async(self) -> None:
        client = None
        notify_started = False
        failure: BaseException | None = None

        try:
            client = await self._scan_and_connect()
            if client is not None and not self.stop_event.is_set():
                await client.start_notify(self.config.notify_uuid, self._on_notification)
                notify_started = True
                if self._callback_error is not None:
                    raise self._callback_error
                self.startup_event.set()

                while not self.stop_event.is_set():
                    if self._callback_error is not None:
                        raise self._callback_error
                    if self._disconnected_event.is_set() or not client.is_connected:
                        raise ConnectionError("BWT901 BLE connection was lost.")
                    await asyncio.sleep(0.05)

                if self._callback_error is not None:
                    raise self._callback_error
        except BaseException as exc:
            failure = exc

        cleanup_errors: list[BaseException] = []
        if client is not None:
            if notify_started and client.is_connected:
                try:
                    await client.stop_notify(self.config.notify_uuid)
                except BaseException as exc:
                    exc.add_note(f"BWT901 cleanup stop_notify: {self.config.device_id}")
                    cleanup_errors.append(exc)
            try:
                await client.disconnect()
            except BaseException as exc:
                exc.add_note(f"BWT901 cleanup disconnect: {self.config.device_id}")
                cleanup_errors.append(exc)

        if cleanup_errors:
            cleanup_failure: BaseException = (
                cleanup_errors[0]
                if len(cleanup_errors) == 1
                else BaseExceptionGroup("BWT901 cleanup failed.", cleanup_errors)
            )
            failure = (
                BaseExceptionGroup(
                    "BWT901 acquisition and cleanup both failed.",
                    [failure, cleanup_failure],
                )
                if failure is not None
                else cleanup_failure
            )

        if failure is not None:
            raise failure

    async def _scan_and_connect(self):
        if self.client_factory is None or self.scanner_factory is None:
            raise RuntimeError("bleak is not installed; BWT901 BLE acquisition is unavailable.")

        acquired = False
        while not self.stop_event.is_set():
            if _BLE_CONNECT_LOCK.acquire(timeout=0.05):
                acquired = True
                break
            await asyncio.sleep(0)
        if not acquired:
            return None

        scanner = None
        client = None
        try:
            loop = asyncio.get_running_loop()
            found_device = loop.create_future()
            requested_address = self.config.address.casefold() or None
            name_filter = self.config.name_filter.casefold()

            def matches(device, advertisement) -> bool:
                if requested_address:
                    return (device.address or "").casefold() == requested_address
                advertised_name = (
                    getattr(advertisement, "local_name", None)
                    or getattr(device, "name", None)
                    or ""
                )
                return name_filter in advertised_name.casefold()

            def device_found(device, advertisement) -> None:
                if not found_device.done() and matches(device, advertisement):
                    found_device.set_result(device)

            scanner = self.scanner_factory(device_found)
            await scanner.start()
            device = await self._wait_for_device(found_device)
            if device is None:
                return None

            self.resolved_address = str(getattr(device, "address", "") or "")
            self.resolved_name = str(getattr(device, "name", "") or self.config.name_filter)

            address_types: list[str | None] = [self.config.windows_address_type]
            if sys.platform == "win32" and self.config.windows_address_type is None:
                address_types = [None, "random", "public"]

            last_not_found: BaseException | None = None
            for address_type in address_types:
                options: dict[str, object] = {
                    "disconnected_callback": self._on_disconnected,
                }
                if sys.platform == "win32" and address_type is not None:
                    options["winrt"] = {"address_type": address_type}

                candidate = self.client_factory(device, **options)
                try:
                    await candidate.connect()
                    client = candidate
                    break
                except BaseException as exc:
                    if self.not_found_error is not None and isinstance(
                        exc, self.not_found_error
                    ):
                        last_not_found = exc
                        with suppress(BaseException):
                            await candidate.disconnect()
                        continue
                    with suppress(BaseException):
                        await candidate.disconnect()
                    raise

            if client is None:
                if last_not_found is not None:
                    raise last_not_found
                raise ConnectionError("BWT901 BLE connection could not be established.")

            return client
        finally:
            if scanner is not None:
                with suppress(BaseException):
                    await scanner.stop()
            _BLE_CONNECT_LOCK.release()

    async def _wait_for_device(self, found_device):
        loop = asyncio.get_running_loop()
        deadline = loop.time() + self.config.scan_timeout_s

        while not self.stop_event.is_set():
            remaining = deadline - loop.time()
            if remaining <= 0:
                target = self.config.address or f"name containing {self.config.name_filter!r}"
                raise TimeoutError(
                    f"BWT901 scan timed out after {self.config.scan_timeout_s:g}s: {target}."
                )
            try:
                return await asyncio.wait_for(
                    asyncio.shield(found_device),
                    timeout=min(0.05, remaining),
                )
            except asyncio.TimeoutError:
                continue
        return None

    def _on_notification(self, _sender, data: bytearray) -> None:
        if self.stop_event.is_set():
            return

        try:
            self.notification_count += 1
            host_monotonic_ns = time.perf_counter_ns()
            host_unix_ns = time.time_ns()
            packets = self.decoder.feed(data)

            for packet in packets:
                record = _record_from_packet(
                    packet,
                    host_monotonic_ns=host_monotonic_ns,
                    host_unix_ns=host_unix_ns,
                )
                try:
                    self.records.put_nowait(record)
                except queue.Full as exc:
                    raise RuntimeError(
                        f"BWT901 record queue is full for {self.config.device_id!r}; "
                        "acquisition stopped."
                    ) from exc
                self.decoded_frame_count += 1
        except BaseException as exc:
            if self._callback_error is None:
                self._callback_error = exc
                self.stop_event.set()

    def _on_disconnected(self, _client) -> None:
        self._disconnected_event.set()


__all__ = [
    "BWT901BLEConfig",
    "BWT901BLEWorker",
    "BWT901Record",
    "DEFAULT_BWT901_NOTIFY_UUID",
    "DEFAULT_BWT901_SCAN_TIMEOUT_S",
]
