"""Small thread-safe finite-history store for live streams."""

from __future__ import annotations

import threading
from collections import deque
from collections.abc import Iterable
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class StreamSchema:
    """Runtime description of one normalized stream.

    ``nominal_rate_hz`` is optional metadata.  A stream may be sampled at a
    known nominal rate (for example Myo EMG at 200 Hz) or may only expose host
    observation timing (for example an asynchronously delivered IMU stream).
    The realtime store itself does not require a nominal rate.
    """

    stream_id: str
    field_keys: tuple[str, ...]
    nominal_rate_hz: float | None = None

    def __post_init__(self) -> None:
        if not self.stream_id:
            raise ValueError("stream_id must not be empty.")
        if not self.field_keys:
            raise ValueError("field_keys must not be empty.")
        if len(set(self.field_keys)) != len(self.field_keys):
            raise ValueError("field_keys must be unique.")
        if self.nominal_rate_hz is not None and self.nominal_rate_hz <= 0:
            raise ValueError("nominal_rate_hz must be positive when provided.")


@dataclass(frozen=True, slots=True)
class StreamSample:
    """One normalized sample before the runtime assigns an ordering index.

    ``host_monotonic_ns`` is the canonical realtime observation coordinate.
    ``host_unix_ns`` is retained for wall-clock audit/alignment, but is not
    used for ordering because the operating system may adjust wall time.
    """

    host_monotonic_ns: int
    host_unix_ns: int
    values: tuple[float, ...]


@dataclass(frozen=True, slots=True)
class StreamRow:
    """One sample retained by :class:`RealtimeStreamStore`.

    ``runtime_index`` is generated by the store and only means strict ordering
    inside this normalized stream.  It is deliberately not called a device or
    sample index.  A counter genuinely supplied by a device/protocol should be
    retained explicitly by that device adapter (for example as a stream field)
    instead of being conflated with this runtime coordinate.
    """

    runtime_index: int
    host_monotonic_ns: int
    host_unix_ns: int
    values: tuple[float, ...]


@dataclass(frozen=True, slots=True)
class StreamSnapshot:
    schema: StreamSchema
    rows: tuple[StreamRow, ...]
    reference_monotonic_ns: int | None


class RealtimeStreamStore:
    """Keep bounded recent history for heterogeneous realtime streams.

    Stable semantics:

    * ``window(stream_id, seconds)`` is always a host-monotonic-time query.
    * ``tail_samples(stream_id, count)`` is always a count/order query.
    * ``nominal_rate_hz`` is optional stream metadata and never determines
      whether the store can retain or query a stream.

    The store deliberately knows nothing about BLE/serial transports, device
    protocols, plotting, persistence, stimulus or synchronization.
    """

    def __init__(
        self,
        schemas: tuple[StreamSchema, ...],
        *,
        retention_seconds: float = 30.0,
        max_rows_per_stream: int = 100_000,
    ) -> None:
        if retention_seconds <= 0:
            raise ValueError("retention_seconds must be positive.")
        if max_rows_per_stream <= 0:
            raise ValueError("max_rows_per_stream must be positive.")
        if not schemas:
            raise ValueError("At least one stream schema is required.")

        by_id = {schema.stream_id: schema for schema in schemas}
        if len(by_id) != len(schemas):
            raise ValueError("stream_id values must be unique.")

        self._schemas = by_id
        self._buffers: dict[str, deque[StreamRow]] = {
            schema.stream_id: deque() for schema in schemas
        }
        self._next_runtime_index: dict[str, int] = {
            schema.stream_id: 0 for schema in schemas
        }
        self._retention_ns = int(float(retention_seconds) * 1_000_000_000)
        self._max_rows_per_stream = int(max_rows_per_stream)
        self._latest_observation_ns: int | None = None
        self._total_rows = 0
        self._lock = threading.RLock()

    @property
    def row_count(self) -> int:
        """Total rows ingested during this store's lifetime."""

        with self._lock:
            return self._total_rows

    @property
    def stream_count(self) -> int:
        return len(self._schemas)

    @property
    def latest_observation_monotonic_ns(self) -> int | None:
        """Latest host-monotonic observation across all streams."""

        with self._lock:
            return self._latest_observation_ns

    def schemas(self) -> tuple[StreamSchema, ...]:
        return tuple(self._schemas.values())

    def schema(self, stream_id: str) -> StreamSchema | None:
        return self._schemas.get(stream_id)

    def append(
        self,
        stream_id: str,
        *,
        host_monotonic_ns: int,
        host_unix_ns: int,
        values: tuple[float, ...],
    ) -> StreamRow:
        """Append one normalized sample and return its retained runtime row."""

        rows = self.append_batch(
            stream_id,
            (
                StreamSample(
                    host_monotonic_ns=int(host_monotonic_ns),
                    host_unix_ns=int(host_unix_ns),
                    values=values,
                ),
            ),
        )
        return rows[0]

    def append_batch(
        self,
        stream_id: str,
        samples: Iterable[StreamSample],
    ) -> tuple[StreamRow, ...]:
        """Append a device/notification batch using one store lock acquisition."""

        schema = self._schemas.get(stream_id)
        if schema is None:
            raise KeyError(f"Unknown stream_id: {stream_id!r}")

        pending = tuple(samples)
        if not pending:
            return ()

        normalized: list[StreamSample] = []
        for sample in pending:
            if len(sample.values) != len(schema.field_keys):
                raise ValueError(
                    f"{stream_id!r} expects {len(schema.field_keys)} values, "
                    f"got {len(sample.values)}."
                )
            normalized.append(
                StreamSample(
                    host_monotonic_ns=int(sample.host_monotonic_ns),
                    host_unix_ns=int(sample.host_unix_ns),
                    values=tuple(float(value) for value in sample.values),
                )
            )

        for previous, current in zip(normalized, normalized[1:]):
            if current.host_monotonic_ns < previous.host_monotonic_ns:
                raise ValueError(
                    f"Non-monotonic host observation time inside batch for {stream_id!r}."
                )

        with self._lock:
            buffer = self._buffers[stream_id]
            if buffer and normalized[0].host_monotonic_ns < buffer[-1].host_monotonic_ns:
                raise ValueError(
                    f"Non-monotonic host observation time for {stream_id!r}: "
                    f"{normalized[0].host_monotonic_ns} after {buffer[-1].host_monotonic_ns}."
                )

            next_index = self._next_runtime_index[stream_id]
            rows = tuple(
                StreamRow(
                    runtime_index=next_index + offset,
                    host_monotonic_ns=sample.host_monotonic_ns,
                    host_unix_ns=sample.host_unix_ns,
                    values=sample.values,
                )
                for offset, sample in enumerate(normalized)
            )
            buffer.extend(rows)
            self._next_runtime_index[stream_id] = next_index + len(rows)
            self._total_rows += len(rows)

            batch_latest = rows[-1].host_monotonic_ns
            if self._latest_observation_ns is None:
                self._latest_observation_ns = batch_latest
            else:
                self._latest_observation_ns = max(self._latest_observation_ns, batch_latest)

            self._prune_locked(self._latest_observation_ns)
            return rows

    def latest(self, stream_id: str) -> StreamRow | None:
        buffer = self._buffers.get(stream_id)
        if buffer is None:
            raise KeyError(f"Unknown stream_id: {stream_id!r}")

        with self._lock:
            return buffer[-1] if buffer else None

    def window(
        self,
        stream_id: str,
        window_seconds: float,
        *,
        reference_monotonic_ns: int | None = None,
    ) -> StreamSnapshot:
        """Return samples observed in the most recent host-time window.

        By default the reference is the latest observation across *all* streams,
        which gives multiple devices a shared realtime reference.  Supplying an
        explicit reference is useful for deterministic consumers/tests.
        """

        if window_seconds <= 0:
            raise ValueError("window_seconds must be positive.")

        schema = self._schemas.get(stream_id)
        if schema is None:
            raise KeyError(f"Unknown stream_id: {stream_id!r}")

        with self._lock:
            reference = (
                self._latest_observation_ns
                if reference_monotonic_ns is None
                else int(reference_monotonic_ns)
            )
            if reference is None:
                return StreamSnapshot(schema, (), None)

            cutoff = reference - int(float(window_seconds) * 1_000_000_000)
            rows = tuple(
                row
                for row in self._buffers[stream_id]
                if cutoff <= row.host_monotonic_ns <= reference
            )
            return StreamSnapshot(schema, rows, reference)

    def tail_samples(self, stream_id: str, count: int) -> StreamSnapshot:
        """Return the latest ``count`` rows without assigning any time meaning."""

        if count < 0:
            raise ValueError("count must not be negative.")

        schema = self._schemas.get(stream_id)
        if schema is None:
            raise KeyError(f"Unknown stream_id: {stream_id!r}")

        with self._lock:
            rows = tuple(self._buffers[stream_id])
            selected = rows[-count:] if count else ()
            return StreamSnapshot(schema, selected, self._latest_observation_ns)

    def _prune_locked(self, reference_monotonic_ns: int) -> None:
        cutoff = reference_monotonic_ns - self._retention_ns
        for buffer in self._buffers.values():
            while buffer and buffer[0].host_monotonic_ns < cutoff:
                buffer.popleft()
            while len(buffer) > self._max_rows_per_stream:
                buffer.popleft()
